export const products = [
  {
    id: 1,
    name: "Ardor Avaitor",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit.Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Ray-Ban",
    category: "Sports",
    gender: "Men",
    weight: "200g",
    quantity: 1,
    image:
      " https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports1.png",
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
    trending: true,
  },
  {
    id: 2,
    name: "Caper Active",
    description:
      "Pellentesque ac tortor sed ipsum feugiat condimentum.Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Persol",
    category: "Sports",
    gender: "Men",
    weight: "100g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports2.png",
    rating: 4.8,
    price: 1299,
    newPrice: 1199,
    trending: true,
  },
  {
    id: 3,
    name: "Alder Street",
    description:
      "Integer et nunc in turpis maximus facilisis ac ac elit.Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Kate Spade",
    category: "Sports",
    gender: "Unisex",
    weight: "750g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports3.png",
    rating: 4.7,
    price: 2999,
    newPrice: 2000,
    trending: true,
  },
  {
    id: 4,
    name: "Corral Round",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna. Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Carrera",
    category: "Sports",
    gender: "Unisex",
    weight: "300g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports4.png",
    rating: 3.8,
    price: 2499,
    newPrice: 2300,
  },
  {
    id: 5,
    name: "Hyperclax Active",
    description:
      "Aenean at velit consequat, faucibus mi id, tempor velit. Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Oakley",
    category: "Sports",
    gender: "Women",
    weight: "900g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports6.png",
    rating: 3.5,
    price: 3999,
    newPrice: 3500,
  },
  {
    id: 6,
    name: "Rose Gold Chase",
    description:
      "Vivamus mattis quam sed libero pretium ullamcorper. Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Ray-Ban",
    category: "Vision",
    gender: "Women",
    weight: "120g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision7.png",
    rating: 4.3,
    price: 2999,
    newPrice: 2599,
  },
  {
    id: 7,
    name: "Full Rim Airflex",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision8.png",
    rating: 4.8,
    price: 4999,
    newPrice: 3999,
  },
  {
    id: 8,
    name: "Mercury Rounded Red",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Vision",
    gender: "Unisex",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision9.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4300,
  },
  {
    id: 9,
    name: "Candyfloss-302",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Ray-Ban",
    category: "Sunglasses",
    gender: "Men",
    weight: "200g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun3.png",
    rating: 4.5,
    price: 1999,
    newPrice: 1899,
  },
  {
    id: 10,
    name: "Phenomenal Mercury-02",
    description:
      "Pellentesque ac tortor sed ipsum feugiat condimentum. Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Persol",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "100g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun4.png",
    rating: 2.8,
    price: 1299,
    newPrice: 1200,
  },
  {
    id: 11,
    name: "Black boss",
    description:
      "Integer et nunc in turpis maximus facilisis ac ac elit. Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Kate Spade",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "750g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun5.png",
    rating: 4.7,
    price: 2999,
    newPrice: 2399,
    trending: true,
  },
  {
    id: 12,
    name: "Blue Ray Wayfarer",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sports",
    gender: "Unisex",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports9.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
  {
    id: 13,
    name: "Pernik",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna. Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "300g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun7.png",
    rating: 3.8,
    price: 2499,
    newPrice: 1599,
  },
  {
    id: 14,
    name: "Silistra",
    description:
      "Aenean at velit consequat, faucibus mi id, tempor velit. Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Oakley",
    category: "Sunglasses",
    gender: "Women",
    weight: "900g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun8.png",
    rating: 3.5,
    price: 3999,
    newPrice: 3599,
  },
  {
    id: 15,
    name: "Full rim acetate black",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    brand: "Ray-Ban",
    category: "Vision",
    gender: "Men",
    weight: "200g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision1.png",
    rating: 4.5,
    price: 1999,
    newPrice: 1900,
  },
  {
    id: 16,
    name: "Ruse",
    description:
      "Fusce sed est nec ipsum convallis semper nec id ipsum. Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Kate Spade",
    category: "Sunglasses",
    gender: "Men",
    weight: "400g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun9.png",
    rating: 4.1,
    price: 1499,
    newPrice: 1350,
  },
  {
    id: 17,
    name: "Yambol",
    description:
      "Vivamus mattis quam sed libero pretium ullamcorper. Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Ray-Ban",
    category: "Sunglasses",
    gender: "Men",
    weight: "130g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun10.png",
    rating: 4.3,
    price: 2999,
    newPrice: 1999,
  },
  {
    id: 18,
    name: "Roadies Rd-202",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Men",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun14.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4799,
  },
  {
    id: 19,
    name: "Burgas",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun11.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4000,
  },
  {
    id: 20,
    name: "Hip Hop Candy",
    description:
      "Fusce sed est nec ipsum convallis semper nec id ipsum. Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Kate Spade",
    category: "Sports",
    gender: "Men",
    weight: "400g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports7.png",
    rating: 4.1,
    price: 1499,
    newPrice: 1399,
    trending: true,
  },
  {
    id: 21,
    name: "Punk Cut Out",
    description:
      "Vivamus mattis quam sed libero pretium ullamcorper. Vivamus mattis quam sed libero pretium ullamcorper.",
    brand: "Ray-Ban",
    category: "Sports",
    gender: "Women",
    weight: "102g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sports8.png",
    rating: 4.3,
    price: 2999,
    newPrice: 2599,
    trending: true,
  },
  {
    id: 22,
    name: "Rounded Gold",
    description:
      "Pellentesque ac tortor sed ipsum feugiat condimentum. Pellentesque ac tortor sed ipsum feugiat condimentum.",
    brand: "Persol",
    category: "Vision",
    gender: "Men",
    weight: "190g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision2.png",
    rating: 2.8,
    price: 1299,
    newPrice: 1000,
    trending: true,
  },
  {
    id: 23,
    name: "Jungle Safari",
    description:
      "Integer et nunc in turpis maximus facilisis ac ac elit. Integer et nunc in turpis maximus facilisis ac ac elit.",
    brand: "Kate Spade",
    category: "Vision",
    gender: "Unisex",
    weight: "750g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision3.png",
    rating: 4.7,
    price: 2999,
    newPrice: 2899,
  },
  {
    id: 24,
    name: "Burgas",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun11.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4700,
  },
  {
    id: 25,
    name: "Sofia",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Women",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun12.png",
    rating: 4.8,
    price: 4999,
    newPrice: 4399,
  },
  {
    id: 26,
    name: "Plovediv",
    description:
      "Donec interdum felis non justo sollicitudin lobortis. Donec interdum felis non justo sollicitudin lobortis.",
    brand: "Carrera",
    category: "Sunglasses",
    gender: "Unisex",
    weight: "550g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/sun13.png",
    rating: 4.8,
    price: 4999,
    newPrice: 3499,
  },
  {
    id: 27,
    name: "Airway Black",
    description:
      "Vestibulum eu tellus sed lorem tristique lacinia ut vel urna. Vestibulum eu tellus sed lorem tristique lacinia ut vel urna.",
    brand: "Carrera",
    category: "Vision",
    gender: "Unisex",
    weight: "300g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision4.png",
    rating: 3.8,
    price: 2499,
    newPrice: 1499,
  },
  {
    id: 28,
    name: "Cat-eyed Gold",
    description:
      "Aenean at velit consequat, faucibus mi id, tempor velit. Aenean at velit consequat, faucibus mi id, tempor velit.",
    brand: "Oakley",
    category: "Vision",
    gender: "Women",
    weight: "900g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision5.png",
    rating: 3.5,
    price: 3999,
    newPrice: 3790,
  },
  {
    id: 29,
    name: "Full Rim Steel Gray",
    description:
      "Fusce sed est nec ipsum convallis semper nec id ipsum. Fusce sed est nec ipsum convallis semper nec id ipsum.",
    brand: "Kate Spade",
    category: "Vision",
    gender: "Men",
    weight: "400g",
    quantity: 1,
    image:
      "https://acsiwxkzzpxnzwnjctqo.supabase.co/storage/v1/object/public/sunglasses/vision6.png",
    rating: 4.1,
    price: 1499,
    newPrice: 1459,
  },
];
